<?php
/**
 * @file
 * Main file for Linkit References module.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function linkit_references_ctools_plugin_directory($module, $plugin) {
  if ($module == 'linkit' && !empty($plugin)) {
    return "plugins/" . $plugin;
  }
}

/**
 * Implements hook_linkit_allowed_field_types().
 */
function linkit_references_linkit_allowed_field_types() {
  $allowed_field_types = array(
    'node_reference',  
    'user_reference',
    'entityreference',
  );
  return $allowed_field_types;
}

/**
 * Implements hook_linkit_allowed_field_widget_types().
 */
function linkit_references_linkit_allowed_field_widget_types() {
  $allowed_field_widget_types = array(
    'node_reference_autocomplete',  
    'user_reference_autocomplete',
    'entityreference_autocomplete',
  );
  return $allowed_field_widget_types;
}